import { ScaledValueLiteralAbsoluteKgPerHRelativeToCollectorAreaKgPerHM2 } from '$lib/openapi/generated/model/scaledValueLiteralAbsoluteKgPerHRelativeToCollectorAreaKgPerHM2';
import { ScaledValueLiteralAbsoluteM2RelativeToDemandM2PerGWh } from '$lib/openapi/generated/model/scaledValueLiteralAbsoluteM2RelativeToDemandM2PerGWh';

export const AreaScalingEnum = ScaledValueLiteralAbsoluteM2RelativeToDemandM2PerGWh.ScalingEnum;
export const MassFlowScalingEnum = ScaledValueLiteralAbsoluteKgPerHRelativeToCollectorAreaKgPerHM2.ScalingEnum;